### ISSUE TITLE
UServiceManager Unit 

### ISSUE THREAD

**Issue by ageu** [daviladanielc/Delphi-WindowsServiceUtils#1]
I got this error when compile a project

[dcc64 Error] uServiceManager.pas(308): E2010 Incompatible types: 'LPENUM_SERVICE_STATUSW' and '_ENUM_SERVICE_STATUSW'
[dcc64 Error] uServiceManager.pas(320): E2010 Incompatible types: 'LPENUM_SERVICE_STATUSW' and '_ENUM_SERVICE_STATUSW'
[dcc64 Error] uServiceManager.pas(1037): E2010 Incompatible types: 'LPENUM_SERVICE_STATUSW' and '_ENUM_SERVICE_STATUSW'
[dcc64 Error] uServiceManager.pas(1045): E2010 Incompatible types: 'LPENUM_SERVICE_STATUSW' and '_ENUM_SERVICE_STATUSW'

Delphi CE 11.3

What is wrong?

**Comment by daviladanielc** [comment]
Maybe there is an issue with Delphi 11.3 and the Windows API. I will check it this week and fix it.

**Comment by EmmanuelTriballier** [comment]
Same error with Delphi 12 :

[dcc32 Erreur] uServiceManager.pas(308): E2010 Types incompatibles : 'LPENUM_SERVICE_STATUSW' et '_ENUM_SERVICE_STATUSW'

[dcc64 Erreur] uServiceManager.pas(308): E2010 Types incompatibles : 'LPENUM_SERVICE_STATUSW' et '_ENUM_SERVICE_STATUSW'

**Comment by daviladanielc** [comment]
Hi, sorry for the delay, but I just uploaded the fix.
